Update load script
Add set -e
Use -z to check if the csgo pid is empty
Re-use the csgo_pid variable

diff --git a/load b/load
--- a/load
+++ b/load
@@ -1,27 +1,26 @@
 #!/bin/sh
 
+set -e
 
 csgo_pid=$(pidof csgo_linux64)
-if [ "$csgo_pid" == "" ]
-then
-	echo -e "\e[31mCSGO needs to be open before you can inject...\e[0m"
-
-	exit
+if [ -z "$csgo_pid" ]; then
+    echo -e "\e[31mCSGO needs to be open before you can inject...\e[0m"
+    exit 1
 fi
 
 if [ ! -d ".git" ]; then
-  echo "We have detected that you have downloaded aimtux-master.zip from the GitHub website. This is the WRONG way to download AimTux. Please download AimTux with the command 'git clone --recursive https://github.com/AimTuxOfficial/AimTux'"
+    echo "We have detected that you have downloaded aimtux-master.zip from the GitHub website. This is the WRONG way to download AimTux. Please download AimTux with the command 'git clone --recursive https://github.com/AimTuxOfficial/AimTux'"
 fi
 
 #Credit: Aixxe @ aixxe.net
-if grep -q libAimTux.so /proc/$(pidof csgo_linux64)/maps; then
-	echo -e "\e[33mAimTux is already injected... Aborting...\e[0m"
-	exit
+if grep -q libAimTux.so /proc/$csgo_pid/maps; then
+    echo -e "\e[33mAimTux is already injected... Aborting...\e[0m"
+    exit
 fi
 
 input="$(
 sudo gdb -n -q -batch \
-  -ex "attach $(pidof csgo_linux64)" \
+  -ex "attach $csgo_pid" \
   -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
   -ex "call \$dlopen(\"$(pwd)/libAimTux.so\", 1)" \
   -ex "detach" \
@@ -31,7 +30,7 @@ sudo gdb -n -q -batch \
 last_line="${input##*$'\n'}"
 
 if [ "$last_line" != "\$1 = (void *) 0x0" ]; then
-	echo -e "\e[32mSuccessfully injected!\e[0m"
+    echo -e "\e[32mSuccessfully injected!\e[0m"
 else
-	echo -e "\e[31mInjection failed, make sure you've compiled...\e[0m"
+    echo -e "\e[31mInjection failed, make sure you've compiled...\e[0m"
 fi
